### ISSUE TITLE
CT unsupported arg in options "undefined"

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/phet-core#117]
```
phet-core : top-level-unit-tests : unbuilt?ea
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1650625337896/phet-core/phet-core-tests.html?ea
39 out of 40 tests passed. 1 failed.
merge: test wrong args failed:
unsupported arg in options "undefined"
at Object.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1650625337896/chipper/dist/js/phet-core/js/mergeTests.js:419:12)

id: Bayes Chrome
Snapshot from 4/22/2022, 5:02:17 AM

----------------------------------

phet-core : top-level-unit-tests : unbuilt?ea&brand=phet-io
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1650625337896/phet-core/phet-core-tests.html?ea&brand=phet-io
39 out of 40 tests passed. 1 failed.
merge: test wrong args failed:
unsupported arg in options "undefined"
at Object.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1650625337896/chipper/dist/js/phet-core/js/mergeTests.js:419:12)

id: Bayes Chrome
Snapshot from 4/22/2022, 5:02:17 AM
```

**Comment by jonathanolson** [comment]
@zepumph is this a failure from https://github.com/phetsims/phet-core/issues/111?

**Comment by zepumph** [comment]
Yes thanks. Fixed above.
